### ISSUE TITLE
可以用于中文NER任务吗？

### ISSUE THREAD

**Issue by haoyumei** [BeyonderXX/MINER#4]
您好，想问下这个模型代码可以用于中文NER任务吗？用于中文NER任务中的话，在生成entity.json文件时，也可以使用Levenshtein方法计算相似的实体吗？一定要用相似的实体去生成对比样本吗，可以只是用同类别的实体去替换生成吗？谢谢~

**Comment by BeyonderXX** [comment]
可以用中文的，但是替换的词的算法要改一改，Levenshtein是OK的。
最好用相似的实体，较大概率生成语义正常的句子，不用相似的，结果可能会略微下降，影响不大。

**Comment by haoyumei** [comment]
好的，感谢回复！~

**Comment by haoyumei** [comment]
您好，学习您的代码时有个疑问还想再请教下，bn_bert_ner.py文件中在模型初始化时定义了信息瓶颈层self.bn_encoder，但在下面的forword()函数中为什么没有调用bn_encoder，我看了其他地方没有看到，是在其他地方调用了吗还是没用到这部分呢？方便的话能帮忙说明下吗?谢谢！~
